pipeline {
    agent any

    stages {
        stage('Compile Java') {
            steps {
                dir('interview/src') {
                    sh 'javac com/interview/questions/Checking_Pipeline.java'
                }
            }
        }

        stage('Run Class') {
            steps {
                dir('interview/src') {
                    sh 'java com.interview.questions.Checking_Pipeline'
                }
            }
        }
    }
}
