pipeline {
    agent any

    stages {
        stage('Compile Java') {
            steps {
                dir('interview/src') {
                    sh 'javac com/interview/questions/checking_pipeline.java'
                }
            }
        }

        stage('Run Class') {
            steps {
                dir('interview/src') {
                    sh 'java com.interview.questions.checking_pipeline'
                }
            }
        }
    }
}
